# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sfpca <- function(model_type, X, Y, Omega_u, Omega_v, alpha_u = 0, alpha_v = 0, lambda_u = 0, lambda_v = 0, P_u = "l1", P_v = "l1", scad_a = 3.7, non_neg = 0L, EPS = 1e-4, MAX_ITER = 1e+3L, solver = "ISTA", SVD = 1L) {
    .Call(`_sfpca_sfpca`, model_type, X, Y, Omega_u, Omega_v, alpha_u, alpha_v, lambda_u, lambda_v, P_u, P_v, scad_a, non_neg, EPS, MAX_ITER, solver, SVD)
}

